import { CONTENT_ASSETS } from "./contents";
import type {
  AssetFamily,
  AssetTag,
  DebrisShape,
  DestructionProfile,
  LotZone,
  Material,
  Prop,
  PropPose,
} from "../structure/types";

export type LotCompat = LotZone | "agricultural" | "roadside" | "yard" | "driveway" | "frontage" | "utility";

export interface RenderBox {
  along: number;
  across: number;
  z: number;
  len: number;
  wid: number;
  h: number;
  top: number;
  left: number;
  right: number;
}

export interface DebrisRecipe {
  remnants: number;
  fragments: number;
  particles: number;
  remnantScale: number;
  pileMass: number;
  shape: DebrisShape;
}

export interface AssetDef {
  id: string;
  family: AssetFamily;
  tags: readonly AssetTag[];
  footprint: { w: number; d: number; h: number };
  collision: { w: number; d: number };
  material: Material;
  hp: number;
  mass: number;
  resistance: number;
  bladeMul: number;
  trackHazard: number;
  cash: number;
  destruction: DestructionProfile;
  debris: DebrisRecipe;
  variants: number;
  boxes: readonly RenderBox[];
  zones: readonly LotCompat[];
  roadsideOk: boolean;
  minClear: number;
  sparks: boolean;
  birdGag: boolean;
  explodeRadius: number;
  explodeImpulse: number;
  explodeDamage: number;
  yawResist: number;
}

const emptyPose = (): PropPose => ({ lean: 0, leanX: 0, leanY: 0, crush: 0, roll: 0 });

function box(
  along: number,
  across: number,
  z: number,
  len: number,
  wid: number,
  h: number,
  top: number,
  left: number,
  right: number,
): RenderBox {
  return { along, across, z, len, wid, h, top, left, right };
}

function debris(
  remnants: number,
  fragments: number,
  particles: number,
  remnantScale: number,
  pileMass: number,
  shape: DebrisShape,
): DebrisRecipe {
  return { remnants, fragments, particles, remnantScale, pileMass, shape };
}

function asset(partial: AssetDef): AssetDef {
  return partial;
}

const MET = { t: 0x8b908c, l: 0x3e4240, r: 0x6d7270 };
const WOOD = { t: 0xc98a4e, l: 0x7a4a24, r: 0xb8733a };
const HAY = { t: 0xd4b45a, l: 0x8a6a28, r: 0xc4a24a };
const GREEN = { t: 0x4a8844, l: 0x244a22, r: 0x3d6a32 };
const RED = { t: 0xc44a40, l: 0x5c241f, r: 0xa03028 };
const DARK = { t: 0x3a3a36, l: 0x1a1a18, r: 0x2a2a28 };
const SIGN = { t: 0xe8d8a0, l: 0x8a7a30, r: 0xd4c56a };
const PUMP = { t: 0xb84840, l: 0x4a1818, r: 0x8a3030 };
const BARREL = { t: 0xe07a2a, l: 0x6a3010, r: 0xce6a22 };
const FOL = { t: 0x5a9a42, l: 0x244820, r: 0x3d6a32 };
const TRUNK = { t: 0x8a6238, l: 0x4a3018, r: 0x6a4428 };

export const ASSET_CATALOG: readonly AssetDef[] = [
  ...CONTENT_ASSETS,
  asset({
    id: "fence",
    family: "legacy",
    tags: ["residential"],
    footprint: { w: 1, d: 0.16, h: 0.85 },
    collision: { w: 1, d: 0.16 },
    material: "wood",
    hp: 9,
    mass: 0.4,
    resistance: 0.2,
    bladeMul: 1.1,
    trackHazard: 0,
    cash: 8,
    destruction: "brittle",
    debris: debris(1, 1, 4, 0.7, 0.15, "beam"),
    variants: 1,
    boxes: [box(0, 0, 0, 1, 0.16, 0.85, WOOD.t, WOOD.l, WOOD.r)],
    zones: ["residential", "yard"],
    roadsideOk: false,
    minClear: 0.2,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "light",
    family: "legacy",
    tags: ["roadside", "tall"],
    footprint: { w: 0.28, d: 0.28, h: 2.7 },
    collision: { w: 0.28, d: 0.28 },
    material: "metal",
    hp: 14,
    mass: 1.1,
    resistance: 0.45,
    bladeMul: 0.9,
    trackHazard: 0.25,
    cash: 12,
    destruction: "bend-snap",
    debris: debris(1, 2, 6, 0.55, 0.2, "beam"),
    variants: 1,
    boxes: [
      box(0, 0, 0, 0.22, 0.22, 2.5, MET.t, MET.l, MET.r),
      box(0, 0, 2.5, 0.5, 0.5, 0.2, SIGN.t, SIGN.l, SIGN.r),
    ],
    zones: ["roadside", "commercial"],
    roadsideOk: true,
    minClear: 0.3,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "camera",
    family: "legacy",
    tags: ["roadside", "tall"],
    footprint: { w: 0.26, d: 0.26, h: 2.2 },
    collision: { w: 0.26, d: 0.26 },
    material: "metal",
    hp: 8,
    mass: 0.5,
    resistance: 0.2,
    bladeMul: 1.2,
    trackHazard: 0,
    cash: 40,
    destruction: "brittle",
    debris: debris(1, 1, 5, 0.45, 0.1, "chunk"),
    variants: 1,
    boxes: [
      box(0, 0, 0, 0.2, 0.2, 2.05, MET.t, MET.l, MET.r),
      box(0.12, 0.02, 1.9, 0.42, 0.22, 0.22, DARK.t, DARK.l, DARK.r),
    ],
    zones: ["roadside", "commercial"],
    roadsideOk: true,
    minClear: 0.25,
    sparks: false,
    birdGag: true,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "car",
    family: "legacy",
    tags: ["commercial"],
    footprint: { w: 1.7, d: 0.85, h: 0.9 },
    collision: { w: 1.7, d: 0.85 },
    material: "metal",
    hp: 28,
    mass: 3.2,
    resistance: 0.7,
    bladeMul: 0.85,
    trackHazard: 0,
    cash: 28,
    destruction: "crush",
    debris: debris(1, 2, 8, 0.85, 0.8, "panel"),
    variants: 4,
    boxes: [],
    zones: ["commercial", "frontage", "driveway"],
    roadsideOk: true,
    minClear: 0.6,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.4,
  }),
  asset({
    id: "dumpster",
    family: "legacy",
    tags: ["commercial"],
    footprint: { w: 0.9, d: 0.7, h: 0.7 },
    collision: { w: 0.9, d: 0.7 },
    material: "metal",
    hp: 22,
    mass: 2.4,
    resistance: 0.8,
    bladeMul: 0.8,
    trackHazard: 0,
    cash: 16,
    destruction: "crush",
    debris: debris(1, 2, 6, 0.8, 0.6, "panel"),
    variants: 1,
    boxes: [box(0, 0, 0, 0.9, 0.7, 0.7, 0x4a8844, 0x244a22, 0x3d6a3a)],
    zones: ["commercial", "industrial", "yard"],
    roadsideOk: false,
    minClear: 0.4,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.2,
  }),
  asset({
    id: "barricade",
    family: "legacy",
    tags: ["roadside"],
    footprint: { w: 1.4, d: 0.28, h: 0.85 },
    collision: { w: 1.4, d: 0.28 },
    material: "wood",
    hp: 12,
    mass: 0.7,
    resistance: 0.35,
    bladeMul: 1,
    trackHazard: 0,
    cash: 8,
    destruction: "brittle",
    debris: debris(1, 1, 5, 0.75, 0.2, "beam"),
    variants: 1,
    boxes: [box(0, 0, 0, 1.4, 0.28, 0.85, WOOD.t, WOOD.l, WOOD.r)],
    zones: ["roadside", "frontage"],
    roadsideOk: true,
    minClear: 0.3,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.15,
  }),
  asset({
    id: "mailbox",
    family: "residential",
    tags: ["residential", "roadside"],
    footprint: { w: 0.28, d: 0.22, h: 1.15 },
    collision: { w: 0.28, d: 0.22 },
    material: "metal",
    hp: 7,
    mass: 0.25,
    resistance: 0.15,
    bladeMul: 1.3,
    trackHazard: 0,
    cash: 10,
    destruction: "bend-snap",
    debris: debris(1, 1, 4, 0.4, 0.08, "chunk"),
    variants: 3,
    boxes: [
      box(0, 0, 0, 0.1, 0.1, 0.95, MET.t, MET.l, MET.r),
      box(0.06, 0, 0.92, 0.32, 0.2, 0.18, 0x4a5a8a, 0x243050, 0x3d5c8a),
    ],
    zones: ["residential", "yard", "frontage"],
    roadsideOk: true,
    minClear: 0.2,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "trash-can",
    family: "residential",
    tags: ["residential"],
    footprint: { w: 0.38, d: 0.38, h: 0.62 },
    collision: { w: 0.38, d: 0.38 },
    material: "metal",
    hp: 6,
    mass: 0.2,
    resistance: 0.08,
    bladeMul: 1.4,
    trackHazard: 0,
    cash: 6,
    destruction: "brittle",
    debris: debris(0, 2, 8, 0.35, 0.05, "chunk"),
    variants: 2,
    boxes: [box(0, 0, 0, 0.34, 0.34, 0.58, MET.t, MET.l, 0x4a6a48)],
    zones: ["residential", "yard", "commercial"],
    roadsideOk: false,
    minClear: 0.2,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "picnic-table",
    family: "residential",
    tags: ["residential"],
    footprint: { w: 1.35, d: 0.85, h: 0.55 },
    collision: { w: 1.35, d: 0.85 },
    material: "wood",
    hp: 14,
    mass: 1.1,
    resistance: 0.35,
    bladeMul: 1,
    trackHazard: 0,
    cash: 12,
    destruction: "crush",
    debris: debris(1, 2, 6, 0.7, 0.35, "panel"),
    variants: 2,
    boxes: [
      box(0, 0, 0.28, 1.3, 0.72, 0.08, WOOD.t, WOOD.l, WOOD.r),
      box(-0.4, 0.28, 0, 0.12, 0.72, 0.28, WOOD.t, WOOD.l, WOOD.r),
      box(0.4, -0.28, 0, 0.12, 0.72, 0.28, WOOD.t, WOOD.l, WOOD.r),
    ],
    zones: ["residential", "yard"],
    roadsideOk: false,
    minClear: 0.4,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.1,
  }),
  asset({
    id: "doghouse",
    family: "residential",
    tags: ["residential"],
    footprint: { w: 0.72, d: 0.62, h: 0.7 },
    collision: { w: 0.72, d: 0.62 },
    material: "wood",
    hp: 11,
    mass: 0.7,
    resistance: 0.25,
    bladeMul: 1.1,
    trackHazard: 0,
    cash: 9,
    destruction: "crush",
    debris: debris(1, 1, 5, 0.6, 0.2, "panel"),
    variants: 2,
    boxes: [
      box(0, 0, 0, 0.68, 0.58, 0.42, WOOD.t, WOOD.l, WOOD.r),
      box(0, 0, 0.4, 0.74, 0.64, 0.22, 0x6e3a30, 0x4a241e, 0x8a4a40),
    ],
    zones: ["residential", "yard"],
    roadsideOk: false,
    minClear: 0.3,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "clothesline",
    family: "residential",
    tags: ["residential", "tall"],
    footprint: { w: 1.8, d: 0.22, h: 1.45 },
    collision: { w: 1.8, d: 0.22 },
    material: "metal",
    hp: 8,
    mass: 0.35,
    resistance: 0.12,
    bladeMul: 1.25,
    trackHazard: 0,
    cash: 8,
    destruction: "bend-snap",
    debris: debris(1, 1, 4, 0.5, 0.1, "beam"),
    variants: 2,
    boxes: [
      box(-0.78, 0, 0, 0.1, 0.1, 1.4, MET.t, MET.l, MET.r),
      box(0.78, 0, 0, 0.1, 0.1, 1.4, MET.t, MET.l, MET.r),
      box(0, 0, 1.28, 1.7, 0.06, 0.05, 0xd8d0b8, 0x8a8270, 0xc4bba4),
    ],
    zones: ["residential", "yard"],
    roadsideOk: false,
    minClear: 0.35,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "swing-set",
    family: "residential",
    tags: ["residential", "tall"],
    footprint: { w: 1.6, d: 0.7, h: 1.55 },
    collision: { w: 1.6, d: 0.7 },
    material: "metal",
    hp: 13,
    mass: 0.9,
    resistance: 0.28,
    bladeMul: 1.1,
    trackHazard: 0,
    cash: 14,
    destruction: "bend-snap",
    debris: debris(1, 2, 6, 0.65, 0.25, "beam"),
    variants: 2,
    boxes: [
      box(-0.7, -0.22, 0, 0.1, 0.1, 1.5, MET.t, MET.l, MET.r),
      box(-0.7, 0.22, 0, 0.1, 0.1, 1.5, MET.t, MET.l, MET.r),
      box(0.7, -0.22, 0, 0.1, 0.1, 1.5, MET.t, MET.l, MET.r),
      box(0.7, 0.22, 0, 0.1, 0.1, 1.5, MET.t, MET.l, MET.r),
      box(0, 0, 1.42, 1.55, 0.12, 0.1, MET.t, MET.l, MET.r),
      box(-0.2, 0, 0.55, 0.28, 0.16, 0.08, WOOD.t, WOOD.l, WOOD.r),
    ],
    zones: ["residential", "yard"],
    roadsideOk: false,
    minClear: 0.45,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.1,
  }),
  asset({
    id: "woodpile",
    family: "residential",
    tags: ["residential", "agricultural"],
    footprint: { w: 1.05, d: 0.55, h: 0.55 },
    collision: { w: 1.05, d: 0.55 },
    material: "wood",
    hp: 10,
    mass: 0.9,
    resistance: 0.3,
    bladeMul: 1.15,
    trackHazard: 0,
    cash: 8,
    destruction: "crush",
    debris: debris(1, 2, 7, 0.7, 0.45, "beam"),
    variants: 2,
    boxes: [
      box(0, 0, 0, 1, 0.5, 0.22, WOOD.t, WOOD.l, WOOD.r),
      box(0.05, 0.02, 0.2, 0.9, 0.42, 0.2, WOOD.t, WOOD.l, WOOD.r),
    ],
    zones: ["residential", "agricultural", "yard"],
    roadsideOk: false,
    minClear: 0.3,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "shed",
    family: "residential",
    tags: ["residential", "agricultural"],
    footprint: { w: 1.7, d: 1.25, h: 1.35 },
    collision: { w: 1.7, d: 1.25 },
    material: "wood",
    hp: 26,
    mass: 3.4,
    resistance: 0.75,
    bladeMul: 0.85,
    trackHazard: 0,
    cash: 22,
    destruction: "panel-collapse",
    debris: debris(2, 2, 8, 0.9, 0.9, "panel"),
    variants: 3,
    boxes: [
      box(0, 0, 0, 1.65, 1.2, 1.05, WOOD.t, WOOD.l, WOOD.r),
      box(0, 0, 1.02, 1.78, 1.3, 0.22, 0x6e3a30, 0x4a241e, 0x8a4a40),
      box(0.72, 0, 0.15, 0.08, 0.42, 0.72, DARK.t, DARK.l, DARK.r),
    ],
    zones: ["residential", "agricultural", "yard"],
    roadsideOk: false,
    minClear: 0.55,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.25,
  }),
  asset({
    id: "hay-bale-square",
    family: "agricultural",
    tags: ["agricultural"],
    footprint: { w: 0.85, d: 0.7, h: 0.7 },
    collision: { w: 0.85, d: 0.7 },
    material: "wood",
    hp: 12,
    mass: 1.6,
    resistance: 0.55,
    bladeMul: 0.95,
    trackHazard: 0,
    cash: 11,
    destruction: "crush",
    debris: debris(1, 1, 6, 0.75, 0.7, "chunk"),
    variants: 2,
    boxes: [box(0, 0, 0, 0.82, 0.66, 0.66, HAY.t, HAY.l, HAY.r)],
    zones: ["agricultural"],
    roadsideOk: false,
    minClear: 0.35,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.05,
  }),
  asset({
    id: "hay-bale-round",
    family: "agricultural",
    tags: ["agricultural", "rollable"],
    footprint: { w: 0.95, d: 0.95, h: 0.9 },
    collision: { w: 0.95, d: 0.95 },
    material: "wood",
    hp: 14,
    mass: 2.1,
    resistance: 0.5,
    bladeMul: 0.9,
    trackHazard: 0,
    cash: 13,
    destruction: "roll",
    debris: debris(1, 1, 5, 0.85, 0.55, "chunk"),
    variants: 2,
    boxes: [box(0, 0, 0, 0.9, 0.9, 0.88, HAY.t, HAY.l, HAY.r)],
    zones: ["agricultural"],
    roadsideOk: false,
    minClear: 0.4,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "water-trough",
    family: "agricultural",
    tags: ["agricultural"],
    footprint: { w: 1.4, d: 0.48, h: 0.42 },
    collision: { w: 1.4, d: 0.48 },
    material: "metal",
    hp: 16,
    mass: 1.4,
    resistance: 0.45,
    bladeMul: 0.95,
    trackHazard: 0,
    cash: 10,
    destruction: "crush",
    debris: debris(1, 1, 5, 0.65, 0.3, "panel"),
    variants: 1,
    boxes: [box(0, 0, 0, 1.35, 0.44, 0.4, MET.t, MET.l, 0x4a6a88)],
    zones: ["agricultural"],
    roadsideOk: false,
    minClear: 0.35,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.2,
  }),
  asset({
    id: "tractor",
    family: "agricultural",
    tags: ["agricultural"],
    footprint: { w: 2.05, d: 1.15, h: 1.25 },
    collision: { w: 2.05, d: 1.15 },
    material: "metal",
    hp: 36,
    mass: 5.5,
    resistance: 1.15,
    bladeMul: 0.7,
    trackHazard: 0,
    cash: 32,
    destruction: "crush",
    debris: debris(2, 2, 8, 0.95, 1.4, "panel"),
    variants: 2,
    boxes: [
      box(-0.15, 0, 0.28, 1.55, 0.85, 0.55, GREEN.t, GREEN.l, GREEN.r),
      box(0.55, 0, 0.7, 0.7, 0.72, 0.48, 0x2c4050, 0x1a2830, 0x3a5568),
      box(-0.7, 0.42, 0, 0.55, 0.22, 0.55, DARK.t, DARK.l, DARK.r),
      box(-0.7, -0.42, 0, 0.55, 0.22, 0.55, DARK.t, DARK.l, DARK.r),
      box(0.7, 0.38, 0, 0.38, 0.18, 0.38, DARK.t, DARK.l, DARK.r),
      box(0.7, -0.38, 0, 0.38, 0.18, 0.38, DARK.t, DARK.l, DARK.r),
    ],
    zones: ["agricultural"],
    roadsideOk: false,
    minClear: 0.7,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.85,
  }),
  asset({
    id: "farm-implement",
    family: "agricultural",
    tags: ["agricultural"],
    footprint: { w: 1.85, d: 0.95, h: 0.85 },
    collision: { w: 1.85, d: 0.95 },
    material: "metal",
    hp: 24,
    mass: 3.6,
    resistance: 1.05,
    bladeMul: 0.75,
    trackHazard: 0,
    cash: 20,
    destruction: "crush",
    debris: debris(1, 2, 6, 0.85, 0.9, "beam"),
    variants: 2,
    boxes: [
      box(0, 0, 0.22, 1.7, 0.7, 0.28, MET.t, MET.l, MET.r),
      box(-0.6, 0.38, 0, 0.35, 0.16, 0.32, DARK.t, DARK.l, DARK.r),
      box(-0.6, -0.38, 0, 0.35, 0.16, 0.32, DARK.t, DARK.l, DARK.r),
      box(0.55, 0, 0.18, 0.16, 0.88, 0.42, 0x6a5410, 0x3a3010, 0x8a6a18),
    ],
    zones: ["agricultural"],
    roadsideOk: false,
    minClear: 0.55,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 1.1,
  }),
  asset({
    id: "grain-bin",
    family: "agricultural",
    tags: ["agricultural", "tall"],
    footprint: { w: 1.35, d: 1.35, h: 2.4 },
    collision: { w: 1.35, d: 1.35 },
    material: "metal",
    hp: 34,
    mass: 4.8,
    resistance: 0.95,
    bladeMul: 0.72,
    trackHazard: 0,
    cash: 28,
    destruction: "panel-collapse",
    debris: debris(2, 2, 8, 0.9, 1.1, "panel"),
    variants: 2,
    boxes: [
      box(0, 0, 0, 1.25, 1.25, 1.9, MET.t, MET.l, MET.r),
      box(0, 0, 1.85, 1.05, 1.05, 0.45, MET.t, MET.l, 0x8b908c),
    ],
    zones: ["agricultural", "industrial"],
    roadsideOk: false,
    minClear: 0.6,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.4,
  }),
  asset({
    id: "pallet-stack",
    family: "commercial",
    tags: ["commercial"],
    footprint: { w: 0.95, d: 0.85, h: 0.7 },
    collision: { w: 0.95, d: 0.85 },
    material: "wood",
    hp: 12,
    mass: 1.2,
    resistance: 0.4,
    bladeMul: 1.05,
    trackHazard: 0,
    cash: 10,
    destruction: "crush",
    debris: debris(1, 2, 6, 0.7, 0.4, "panel"),
    variants: 2,
    boxes: [
      box(0, 0, 0, 0.9, 0.8, 0.16, WOOD.t, WOOD.l, WOOD.r),
      box(0, 0, 0.16, 0.88, 0.78, 0.16, WOOD.t, WOOD.l, WOOD.r),
      box(0, 0, 0.32, 0.86, 0.76, 0.16, WOOD.t, WOOD.l, WOOD.r),
    ],
    zones: ["commercial", "industrial", "yard"],
    roadsideOk: false,
    minClear: 0.35,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.15,
  }),
  asset({
    id: "crate-stack",
    family: "commercial",
    tags: ["commercial"],
    footprint: { w: 0.8, d: 0.7, h: 0.85 },
    collision: { w: 0.8, d: 0.7 },
    material: "wood",
    hp: 10,
    mass: 0.9,
    resistance: 0.3,
    bladeMul: 1.15,
    trackHazard: 0,
    cash: 9,
    destruction: "brittle",
    debris: debris(1, 2, 7, 0.6, 0.25, "chunk"),
    variants: 2,
    boxes: [
      box(-0.12, 0, 0, 0.5, 0.48, 0.38, WOOD.t, WOOD.l, WOOD.r),
      box(0.16, 0.04, 0.36, 0.48, 0.46, 0.4, 0xc4bba4, 0x8a8270, 0xa88850),
    ],
    zones: ["commercial", "industrial", "yard"],
    roadsideOk: false,
    minClear: 0.3,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "fuel-pump",
    family: "commercial",
    tags: ["commercial", "explosive"],
    footprint: { w: 0.55, d: 0.45, h: 1.45 },
    collision: { w: 0.55, d: 0.45 },
    material: "metal",
    hp: 18,
    mass: 1.5,
    resistance: 0.5,
    bladeMul: 1,
    trackHazard: 0,
    cash: 24,
    destruction: "explosive",
    debris: debris(1, 2, 10, 0.55, 0.35, "chunk"),
    variants: 2,
    boxes: [
      box(0, 0, 0, 0.5, 0.4, 1.15, PUMP.t, PUMP.l, PUMP.r),
      box(0, 0, 1.12, 0.42, 0.34, 0.22, MET.t, MET.l, MET.r),
    ],
    zones: ["commercial", "frontage"],
    roadsideOk: false,
    minClear: 0.4,
    sparks: false,
    birdGag: false,
    explodeRadius: 3.2,
    explodeImpulse: 5.4,
    explodeDamage: 20,
    yawResist: 0.2,
  }),
  asset({
    id: "vending",
    family: "commercial",
    tags: ["commercial"],
    footprint: { w: 0.55, d: 0.42, h: 1.25 },
    collision: { w: 0.55, d: 0.42 },
    material: "metal",
    hp: 16,
    mass: 1.3,
    resistance: 0.55,
    bladeMul: 0.95,
    trackHazard: 0,
    cash: 14,
    destruction: "crush",
    debris: debris(1, 1, 6, 0.6, 0.3, "panel"),
    variants: 3,
    boxes: [
      box(0, 0, 0, 0.5, 0.38, 1.2, RED.t, RED.l, RED.r),
      box(0.02, 0, 0.55, 0.36, 0.08, 0.42, 0x2a3a48, 0x1a1410, 0x3e5868),
    ],
    zones: ["commercial", "frontage"],
    roadsideOk: false,
    minClear: 0.3,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.15,
  }),
  asset({
    id: "hvac",
    family: "commercial",
    tags: ["commercial", "utility"],
    footprint: { w: 0.95, d: 0.8, h: 0.7 },
    collision: { w: 0.95, d: 0.8 },
    material: "metal",
    hp: 18,
    mass: 1.8,
    resistance: 0.6,
    bladeMul: 0.9,
    trackHazard: 0,
    cash: 15,
    destruction: "crush",
    debris: debris(1, 2, 6, 0.7, 0.45, "panel"),
    variants: 1,
    boxes: [
      box(0, 0, 0, 0.9, 0.75, 0.55, MET.t, MET.l, MET.r),
      box(0, 0, 0.52, 0.7, 0.55, 0.12, MET.t, MET.l, 0x8b908c),
    ],
    zones: ["commercial", "industrial", "yard"],
    roadsideOk: false,
    minClear: 0.35,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.25,
  }),
  asset({
    id: "utility-cabinet",
    family: "commercial",
    tags: ["utility", "commercial"],
    footprint: { w: 0.7, d: 0.4, h: 1.05 },
    collision: { w: 0.7, d: 0.4 },
    material: "metal",
    hp: 17,
    mass: 1.2,
    resistance: 0.5,
    bladeMul: 1,
    trackHazard: 0,
    cash: 13,
    destruction: "brittle",
    debris: debris(1, 1, 6, 0.55, 0.25, "panel"),
    variants: 2,
    boxes: [box(0, 0, 0, 0.65, 0.36, 1, 0x6a7a48, 0x3a4428, 0x5a6a3a)],
    zones: ["commercial", "industrial", "utility", "frontage"],
    roadsideOk: true,
    minClear: 0.3,
    sparks: true,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.15,
  }),
  asset({
    id: "propane-tank",
    family: "commercial",
    tags: ["commercial", "explosive"],
    footprint: { w: 0.7, d: 0.55, h: 0.85 },
    collision: { w: 0.7, d: 0.55 },
    material: "metal",
    hp: 15,
    mass: 1.4,
    resistance: 0.4,
    bladeMul: 1.05,
    trackHazard: 0,
    cash: 20,
    destruction: "explosive",
    debris: debris(1, 2, 10, 0.5, 0.3, "chunk"),
    variants: 2,
    boxes: [
      box(0, 0, 0, 0.62, 0.48, 0.72, 0xc8c0a8, 0x6a6458, 0xa3a08e),
      box(0, 0, 0.7, 0.18, 0.18, 0.12, MET.t, MET.l, MET.r),
    ],
    zones: ["commercial", "agricultural", "yard"],
    roadsideOk: false,
    minClear: 0.35,
    sparks: false,
    birdGag: false,
    explodeRadius: 3.5,
    explodeImpulse: 5.8,
    explodeDamage: 24,
    yawResist: 0.1,
  }),
  asset({
    id: "stop-sign",
    family: "roadside",
    tags: ["roadside", "tall"],
    footprint: { w: 0.22, d: 0.22, h: 2.05 },
    collision: { w: 0.22, d: 0.22 },
    material: "metal",
    hp: 9,
    mass: 0.35,
    resistance: 0.18,
    bladeMul: 1.2,
    trackHazard: 0,
    cash: 11,
    destruction: "bend-snap",
    debris: debris(1, 1, 4, 0.4, 0.08, "panel"),
    variants: 1,
    boxes: [
      box(0, 0, 0, 0.1, 0.1, 1.65, MET.t, MET.l, MET.r),
      box(0, 0, 1.55, 0.48, 0.08, 0.48, RED.t, RED.l, RED.r),
    ],
    zones: ["roadside", "frontage"],
    roadsideOk: true,
    minClear: 0.25,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "fire-hydrant",
    family: "roadside",
    tags: ["roadside", "utility"],
    footprint: { w: 0.32, d: 0.32, h: 0.72 },
    collision: { w: 0.32, d: 0.32 },
    material: "metal",
    hp: 20,
    mass: 1.6,
    resistance: 0.9,
    bladeMul: 0.8,
    trackHazard: 0,
    cash: 12,
    destruction: "crush",
    debris: debris(1, 1, 5, 0.45, 0.35, "chunk"),
    variants: 1,
    boxes: [box(0, 0, 0, 0.28, 0.28, 0.68, RED.t, RED.l, RED.r)],
    zones: ["roadside", "commercial", "residential"],
    roadsideOk: true,
    minClear: 0.25,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.3,
  }),
  asset({
    id: "power-pole",
    family: "roadside",
    tags: ["roadside", "tall", "utility"],
    footprint: { w: 0.32, d: 0.32, h: 3.2 },
    collision: { w: 0.32, d: 0.32 },
    material: "wood",
    hp: 18,
    mass: 1.8,
    resistance: 0.55,
    bladeMul: 0.85,
    trackHazard: 0.55,
    cash: 14,
    destruction: "bend-snap",
    debris: debris(1, 2, 6, 0.7, 0.4, "beam"),
    variants: 1,
    boxes: [
      box(0, 0, 0, 0.26, 0.26, 3.05, TRUNK.t, TRUNK.l, TRUNK.r),
      box(0, 0, 2.85, 1.15, 0.1, 0.1, WOOD.t, WOOD.l, WOOD.r),
    ],
    zones: ["roadside"],
    roadsideOk: true,
    minClear: 0.35,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "transformer",
    family: "roadside",
    tags: ["roadside", "utility"],
    footprint: { w: 0.55, d: 0.45, h: 0.85 },
    collision: { w: 0.55, d: 0.45 },
    material: "metal",
    hp: 16,
    mass: 1.5,
    resistance: 0.6,
    bladeMul: 0.95,
    trackHazard: 0,
    cash: 16,
    destruction: "brittle",
    debris: debris(1, 1, 7, 0.55, 0.3, "chunk"),
    variants: 1,
    boxes: [box(0, 0, 0, 0.5, 0.4, 0.8, 0x6a7a38, 0x3a4420, 0x5a6a30)],
    zones: ["roadside", "utility", "industrial"],
    roadsideOk: true,
    minClear: 0.3,
    sparks: true,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.2,
  }),
  asset({
    id: "guardrail",
    family: "roadside",
    tags: ["roadside"],
    footprint: { w: 1.7, d: 0.18, h: 0.55 },
    collision: { w: 1.7, d: 0.18 },
    material: "metal",
    hp: 14,
    mass: 0.8,
    resistance: 0.4,
    bladeMul: 1,
    trackHazard: 0,
    cash: 8,
    destruction: "bend-snap",
    debris: debris(1, 1, 4, 0.7, 0.2, "beam"),
    variants: 1,
    boxes: [box(0, 0, 0.18, 1.65, 0.12, 0.28, MET.t, MET.l, MET.r)],
    zones: ["roadside"],
    roadsideOk: true,
    minClear: 0.2,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.05,
  }),
  asset({
    id: "traffic-barrel",
    family: "roadside",
    tags: ["roadside", "rollable"],
    footprint: { w: 0.42, d: 0.42, h: 0.7 },
    collision: { w: 0.42, d: 0.42 },
    material: "metal",
    hp: 8,
    mass: 0.35,
    resistance: 0.12,
    bladeMul: 1.3,
    trackHazard: 0,
    cash: 7,
    destruction: "roll",
    debris: debris(1, 1, 5, 0.5, 0.1, "chunk"),
    variants: 2,
    boxes: [box(0, 0, 0, 0.38, 0.38, 0.66, BARREL.t, BARREL.l, BARREL.r)],
    zones: ["roadside", "frontage", "commercial"],
    roadsideOk: true,
    minClear: 0.25,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "billboard",
    family: "roadside",
    tags: ["roadside", "commercial", "tall"],
    footprint: { w: 2.4, d: 0.35, h: 2.6 },
    collision: { w: 2.4, d: 0.35 },
    material: "metal",
    hp: 22,
    mass: 2.8,
    resistance: 0.55,
    bladeMul: 0.9,
    trackHazard: 0,
    cash: 26,
    destruction: "panel-collapse",
    debris: debris(2, 1, 7, 1.1, 0.7, "panel"),
    variants: 3,
    boxes: [
      box(-0.85, 0, 0, 0.16, 0.16, 2.05, MET.t, MET.l, MET.r),
      box(0.85, 0, 0, 0.16, 0.16, 2.05, MET.t, MET.l, MET.r),
      box(0, 0, 1.85, 2.3, 0.12, 0.7, SIGN.t, 0x3a5a38, 0x4a74a4),
    ],
    zones: ["roadside", "commercial"],
    roadsideOk: true,
    minClear: 0.6,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.2,
  }),
  asset({
    id: "shrub",
    family: "vegetation",
    tags: ["vegetation", "residential"],
    footprint: { w: 0.7, d: 0.7, h: 0.65 },
    collision: { w: 0.55, d: 0.55 },
    material: "wood",
    hp: 6,
    mass: 0.25,
    resistance: 0.1,
    bladeMul: 1.35,
    trackHazard: 0,
    cash: 5,
    destruction: "crush",
    debris: debris(0, 1, 6, 0.4, 0.12, "chunk"),
    variants: 3,
    boxes: [box(0, 0, 0, 0.62, 0.62, 0.58, FOL.t, FOL.l, FOL.r)],
    zones: ["residential", "yard", "agricultural"],
    roadsideOk: false,
    minClear: 0.25,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "sapling",
    family: "vegetation",
    tags: ["vegetation", "tall"],
    footprint: { w: 0.45, d: 0.45, h: 1.55 },
    collision: { w: 0.28, d: 0.28 },
    material: "wood",
    hp: 8,
    mass: 0.3,
    resistance: 0.15,
    bladeMul: 1.2,
    trackHazard: 0,
    cash: 6,
    destruction: "bend-snap",
    debris: debris(1, 1, 5, 0.45, 0.1, "beam"),
    variants: 2,
    boxes: [
      box(0, 0, 0, 0.14, 0.14, 0.95, TRUNK.t, TRUNK.l, TRUNK.r),
      box(0, 0, 0.75, 0.5, 0.5, 0.7, FOL.t, FOL.l, FOL.r),
    ],
    zones: ["residential", "yard", "agricultural"],
    roadsideOk: false,
    minClear: 0.3,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0,
  }),
  asset({
    id: "mature-tree",
    family: "vegetation",
    tags: ["vegetation", "tall"],
    footprint: { w: 1.15, d: 1.15, h: 2.9 },
    collision: { w: 0.45, d: 0.45 },
    material: "wood",
    hp: 28,
    mass: 3.8,
    resistance: 0.7,
    bladeMul: 0.8,
    trackHazard: 0,
    cash: 18,
    destruction: "topple",
    debris: debris(1, 2, 8, 1.15, 0.8, "beam"),
    variants: 3,
    boxes: [
      box(0, 0, 0, 0.38, 0.38, 1.55, TRUNK.t, TRUNK.l, TRUNK.r),
      box(0, 0, 1.35, 1.2, 1.2, 1.35, FOL.t, FOL.l, FOL.r),
    ],
    zones: ["residential", "yard", "agricultural"],
    roadsideOk: false,
    minClear: 0.55,
    sparks: false,
    birdGag: false,
    explodeRadius: 0,
    explodeImpulse: 0,
    explodeDamage: 0,
    yawResist: 0.15,
  }),
];

const BY_ID = new Map(ASSET_CATALOG.map((a) => [a.id, a]));

export const NEW_ASSET_IDS = ASSET_CATALOG.filter((a) => a.family !== "legacy").map((a) => a.id);

export function getAsset(id: string): AssetDef {
  const found = BY_ID.get(id);
  if (!found) throw new Error(`Unknown asset ${id}`);
  return found;
}

export function tryAsset(id: string): AssetDef | undefined {
  return BY_ID.get(id);
}

export function assetsByFamily(family: AssetFamily): AssetDef[] {
  return ASSET_CATALOG.filter((a) => a.family === family);
}

export interface CatalogIssue {
  code: string;
  detail: string;
}

export function validateCatalog(defs: readonly AssetDef[] = ASSET_CATALOG): { ok: boolean; issues: CatalogIssue[] } {
  const issues: CatalogIssue[] = [];
  const seen = new Set<string>();
  for (const d of defs) {
    if (seen.has(d.id)) issues.push({ code: "dup", detail: `duplicate id ${d.id}` });
    seen.add(d.id);
    if (!d.id.trim()) issues.push({ code: "id", detail: "empty asset id" });
    if (d.footprint.w <= 0 || d.footprint.d <= 0 || d.footprint.h <= 0) {
      issues.push({ code: "footprint", detail: `${d.id} has a non-positive footprint` });
    }
    if (d.hp <= 0 || d.mass <= 0) issues.push({ code: "stats", detail: `${d.id} needs positive hp and mass` });
    if (d.variants < 1) issues.push({ code: "variant", detail: `${d.id} needs at least one variant` });
    if (d.zones.length === 0) issues.push({ code: "zone", detail: `${d.id} has no compatible zones` });
    if (d.cash < 0) issues.push({ code: "cash", detail: `${d.id} cash is negative` });
    if (d.destruction === "explosive" && d.explodeRadius <= 0) {
      issues.push({ code: "explode", detail: `${d.id} explosive profile missing radius` });
    }
  }
  return { ok: issues.length === 0, issues };
}

let propSeq = 1;

export function resetPropIds(): void {
  propSeq = 1;
}

export function spawnAsset(
  assetId: string,
  x: number,
  y: number,
  heading = 0,
  variant = 0,
  size?: { w: number; d: number },
): Prop {
  const def = getAsset(assetId);
  const w = size?.w ?? def.footprint.w;
  const d = size?.d ?? def.footprint.d;
  return {
    id: propSeq++,
    assetId: def.id,
    kind: def.id,
    variant: ((variant % def.variants) + def.variants) % def.variants,
    x,
    y,
    w,
    d,
    hp: def.hp,
    maxHp: def.hp,
    heading,
    elev: 0,
    broken: false,
    material: def.material,
    pose: emptyPose(),
    vx: 0,
    vy: 0,
    omega: 0,
  };
}

export function propDef(prop: Prop): AssetDef {
  return getAsset(prop.assetId);
}
